---
- name: Install, configure and start avahi
  hosts: pyhole
  become: True
  tasks:

    - name: Install avahi-daemon
      apt:
        name: avahi-daemon
        update_cache: yes

    - name: Start avahi-daemon
      service:
        name: avahi-daemon
        state: started
